### ISSUE TITLE
Написать отчеты по летней практике

### ISSUE THREAD

**Issue by geogreck** [bmstu-iu9/ptp2022-8-todo-list#119]

**Comment by Mazdaywik** [comment]
Это надо было вносить в TODO-список. И прокачивать персонажа выполнением тудушки. 😉 Впрочем, одно другому не мешает.

Есть такая методология разработки: [догфуд](https://en.wikipedia.org/wiki/Eating_your_own_dog_food).

**Comment by geogreck** [comment]
@uma-op не увидел pull request!

**Comment by uma-op** [comment]
@geogreck извини
