### ISSUE TITLE
Перенести данные со старого репозитория

### ISSUE THREAD

**Issue by geogreck** [bmstu-iu9/ptp2022-8-todo-list#2]

**Comment by Mazdaywik** [comment]
На самом деле, можно перенести данные со старого репозитория с сохранением всей истории. Готов показать, как, если старый репозиторий доступен публично.

**Comment by stewkk** [comment]
> На самом деле, можно перенести данные со старого репозитория с сохранением всей истории. Готов показать, как, если старый репозиторий доступен публично.

[Старый репозиторий](https://github.com/stewkk/minimal-login-page)
Мы бы хотели просто перенести часть файлов, потому что прошлый репозиторий был пробный, и мы не особо старались над комментариями к коммитам :)

Но, ради интереса, это делается через `git merge` (с сохранением только истории коммитов)?

**Comment by Mazdaywik** [comment]
Команда `git merge` там безусловно будет:
```bash
git checkout -b old-repo
git remote add stewkk-mlp https://github.com/stewkk/minimal-login-page
git fetch --all
git merge --allow-unrelated-histories stewkk-mlp/main
```
После чего разрешаете конфликты в файлах `.gitignore` и `LICENSE` и завершаете слияние:
```bash
git add .gitignore LICENSE
```
После чего в ветке `old-repo` можно сделать дополнительные правки и сделать pull request.

Поскольку у обоих репозиториев нет общей истории, у `git merge` нужно использовать опцию `--allow-unrelated-histories`.

**Comment by geogreck** [comment]
closes #3
