### ISSUE TITLE
Не работает команда make lint

### ISSUE THREAD

**Issue by geogreck** [bmstu-iu9/ptp2022-8-todo-list#26]
![Screenshot_from_2022-07-10_12-08-19](https://user-images.githubusercontent.com/74151984/178138635-b6634c4a-2ee2-41b4-8a66-8f24b287e55c.png)

**Comment by stewkk** [comment]
Кинь вывод `docker build --target lint .`

**Comment by geogreck** [comment]
![image](https://user-images.githubusercontent.com/74151984/178138856-f3ecfc32-c88d-43c2-8a93-b4e8579a6e74.png)
