### ISSUE TITLE
Несовместимость локального запуска и запуска в docker 

### ISSUE THREAD

**Issue by stewkk** [bmstu-iu9/ptp2022-8-todo-list#43]
1. `yarn dev`
2. `make` в корне

Получаем постоянные падения и перезапуски контейнеров:
![image](https://user-images.githubusercontent.com/43303621/179362115-170bc8dc-4f62-4e37-964b-564a51ab98a3.png)

**Comment by geogreck** [comment]
Единственное решение - выводить запуск через yarn и make на разные порты, не уверен, что это вообще нужно
