### ISSUE TITLE
Дальшейные улучшения списка дел

### ISSUE THREAD

**Issue by geogreck** [bmstu-iu9/ptp2022-8-todo-list#53]
Задачи первой важности:
- Реализация модальной формы редактирования задачи
- Сортировка задач по выбранным лейблам
- Убрать кнопку редактирования
- Добавить кнопку архивирования
- Сделать открытие формы редактирования более интуитивным
- Выделять архивированные задачи визуально
- Список продолжается...

**Comment by geogreck** [comment]
Нашелся баг с добавлением лейблов. Новые лейблы добавляются плохо и криво. Мда. Стыдно.

**Comment by Mazdaywik** [comment]
Можно сделать список чек-листом:
```markdown
Задачи первой важности:
- [ ] Реализация модальной формы редактирования задачи
- [ ] Сортировка задач по выбранным лейблам
```

Выглядит как

> Задачи первой важности:
> - [ ] Реализация модальной формы редактирования задачи
> - [ ] Сортировка задач по выбранным лейблам
