### ISSUE TITLE
Требуется доработка контракта api

### ISSUE THREAD

**Issue by stewkk** [bmstu-iu9/ptp2022-8-todo-list#57]
Необходимо договориться с фронтендерами насчет набора полей объектов `Item`, `Character` и задокументировать это в контракте:
https://github.com/bmstu-iu9/ptp2022-8-todo-list/blob/e2421e522cdaa0ceb520bd7df5482fb2af8cabfc/docs/openapi.yml#L411-L416

**Comment by geogreck** [comment]
Предлагаю следующую схему `item`
```ts
type item = {
    id: number
    name: string
    imageSrc: string
    description: string
    price: number
    category: string
    rarity: Rarity
    state: ItemState
}

type ItemState = "store" | "equipped" | "inventoried"
type Rarity = 'common' | 'rare' | 'epic' | 'legendary'
```

**Comment by geogreck** [comment]
@OkDenAl внёс изменение в тип. Добавлено поле состояния предмета:
```ts
type ItemState = "store" | "equipped" | "inventoried"
```
