### ISSUE TITLE
Решить проблему с загрузкой фотографий в магазин

### ISSUE THREAD

**Issue by viacheslavek** [bmstu-iu9/ptp2022-8-todo-list#67]
При загрузке магазина на js из-за особенностей парсела не высвечиваются картинки

**Comment by viacheslavek** [comment]
решение: хостить картинки на сервере

**Comment by geogreck** [comment]
Для начала предлагаю все изображения предметов переместить в папку `assets`

**Comment by geogreck** [comment]
> решение: хостить картинки на сервере

https://wg.grechkogv.ru/assets/
